/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ACallFunctionExpr6 extends PExpr6
{
    private PCallFunction _callFunction_;

    public ACallFunctionExpr6()
    {
        // Constructor
    }

    public ACallFunctionExpr6(
        @SuppressWarnings("hiding") PCallFunction _callFunction_)
    {
        // Constructor
        setCallFunction(_callFunction_);

    }

    @Override
    public Object clone()
    {
        return new ACallFunctionExpr6(
            cloneNode(this._callFunction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallFunctionExpr6(this);
    }

    public PCallFunction getCallFunction()
    {
        return this._callFunction_;
    }

    public void setCallFunction(PCallFunction node)
    {
        if(this._callFunction_ != null)
        {
            this._callFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._callFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._callFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._callFunction_ == child)
        {
            this._callFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._callFunction_ == oldChild)
        {
            setCallFunction((PCallFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
