/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIaffectationInst extends PInst
{
    private PIaffectation _iaffectation_;

    public AIaffectationInst()
    {
        // Constructor
    }

    public AIaffectationInst(
        @SuppressWarnings("hiding") PIaffectation _iaffectation_)
    {
        // Constructor
        setIaffectation(_iaffectation_);

    }

    @Override
    public Object clone()
    {
        return new AIaffectationInst(
            cloneNode(this._iaffectation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIaffectationInst(this);
    }

    public PIaffectation getIaffectation()
    {
        return this._iaffectation_;
    }

    public void setIaffectation(PIaffectation node)
    {
        if(this._iaffectation_ != null)
        {
            this._iaffectation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iaffectation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iaffectation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iaffectation_ == child)
        {
            this._iaffectation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iaffectation_ == oldChild)
        {
            setIaffectation((PIaffectation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
