/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIblockInst extends PInst
{
    private PIblock _iblock_;

    public AIblockInst()
    {
        // Constructor
    }

    public AIblockInst(
        @SuppressWarnings("hiding") PIblock _iblock_)
    {
        // Constructor
        setIblock(_iblock_);

    }

    @Override
    public Object clone()
    {
        return new AIblockInst(
            cloneNode(this._iblock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIblockInst(this);
    }

    public PIblock getIblock()
    {
        return this._iblock_;
    }

    public void setIblock(PIblock node)
    {
        if(this._iblock_ != null)
        {
            this._iblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iblock_ == child)
        {
            this._iblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iblock_ == oldChild)
        {
            setIblock((PIblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
