/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIcallFunction extends PIcallFunction
{
    private PCallFunction _callFunction_;
    private TSemicolon _semicolon_;

    public AIcallFunction()
    {
        // Constructor
    }

    public AIcallFunction(
        @SuppressWarnings("hiding") PCallFunction _callFunction_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setCallFunction(_callFunction_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AIcallFunction(
            cloneNode(this._callFunction_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIcallFunction(this);
    }

    public PCallFunction getCallFunction()
    {
        return this._callFunction_;
    }

    public void setCallFunction(PCallFunction node)
    {
        if(this._callFunction_ != null)
        {
            this._callFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._callFunction_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._callFunction_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._callFunction_ == child)
        {
            this._callFunction_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._callFunction_ == oldChild)
        {
            setCallFunction((PCallFunction) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
