/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIreturnInst extends PInst
{
    private PIreturn _ireturn_;

    public AIreturnInst()
    {
        // Constructor
    }

    public AIreturnInst(
        @SuppressWarnings("hiding") PIreturn _ireturn_)
    {
        // Constructor
        setIreturn(_ireturn_);

    }

    @Override
    public Object clone()
    {
        return new AIreturnInst(
            cloneNode(this._ireturn_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIreturnInst(this);
    }

    public PIreturn getIreturn()
    {
        return this._ireturn_;
    }

    public void setIreturn(PIreturn node)
    {
        if(this._ireturn_ != null)
        {
            this._ireturn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ireturn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ireturn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ireturn_ == child)
        {
            this._ireturn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ireturn_ == oldChild)
        {
            setIreturn((PIreturn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
