/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIwhileInst extends PInst
{
    private PIwhile _iwhile_;

    public AIwhileInst()
    {
        // Constructor
    }

    public AIwhileInst(
        @SuppressWarnings("hiding") PIwhile _iwhile_)
    {
        // Constructor
        setIwhile(_iwhile_);

    }

    @Override
    public Object clone()
    {
        return new AIwhileInst(
            cloneNode(this._iwhile_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIwhileInst(this);
    }

    public PIwhile getIwhile()
    {
        return this._iwhile_;
    }

    public void setIwhile(PIwhile node)
    {
        if(this._iwhile_ != null)
        {
            this._iwhile_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iwhile_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iwhile_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iwhile_ == child)
        {
            this._iwhile_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iwhile_ == oldChild)
        {
            setIwhile((PIwhile) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
