/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALDeclarationVarBOptLDeclarationVarBOpt extends PLDeclarationVarBOpt
{
    private PLDeclarationVar _lDeclarationVar_;
    private TSemicolon _semicolon_;

    public ALDeclarationVarBOptLDeclarationVarBOpt()
    {
        // Constructor
    }

    public ALDeclarationVarBOptLDeclarationVarBOpt(
        @SuppressWarnings("hiding") PLDeclarationVar _lDeclarationVar_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setLDeclarationVar(_lDeclarationVar_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ALDeclarationVarBOptLDeclarationVarBOpt(
            cloneNode(this._lDeclarationVar_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALDeclarationVarBOptLDeclarationVarBOpt(this);
    }

    public PLDeclarationVar getLDeclarationVar()
    {
        return this._lDeclarationVar_;
    }

    public void setLDeclarationVar(PLDeclarationVar node)
    {
        if(this._lDeclarationVar_ != null)
        {
            this._lDeclarationVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lDeclarationVar_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lDeclarationVar_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lDeclarationVar_ == child)
        {
            this._lDeclarationVar_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lDeclarationVar_ == oldChild)
        {
            setLDeclarationVar((PLDeclarationVar) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
