/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALExprBLExprB extends PLExprB
{
    private TVrg _vrg_;
    private PExpr _expr_;
    private PLExprB _lExprB_;

    public ALExprBLExprB()
    {
        // Constructor
    }

    public ALExprBLExprB(
        @SuppressWarnings("hiding") TVrg _vrg_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") PLExprB _lExprB_)
    {
        // Constructor
        setVrg(_vrg_);

        setExpr(_expr_);

        setLExprB(_lExprB_);

    }

    @Override
    public Object clone()
    {
        return new ALExprBLExprB(
            cloneNode(this._vrg_),
            cloneNode(this._expr_),
            cloneNode(this._lExprB_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALExprBLExprB(this);
    }

    public TVrg getVrg()
    {
        return this._vrg_;
    }

    public void setVrg(TVrg node)
    {
        if(this._vrg_ != null)
        {
            this._vrg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vrg_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public PLExprB getLExprB()
    {
        return this._lExprB_;
    }

    public void setLExprB(PLExprB node)
    {
        if(this._lExprB_ != null)
        {
            this._lExprB_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lExprB_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vrg_)
            + toString(this._expr_)
            + toString(this._lExprB_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vrg_ == child)
        {
            this._vrg_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._lExprB_ == child)
        {
            this._lExprB_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vrg_ == oldChild)
        {
            setVrg((TVrg) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._lExprB_ == oldChild)
        {
            setLExprB((PLExprB) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
