/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALInstLInst extends PLInst
{
    private PInst _inst_;
    private PLInst _lInst_;

    public ALInstLInst()
    {
        // Constructor
    }

    public ALInstLInst(
        @SuppressWarnings("hiding") PInst _inst_,
        @SuppressWarnings("hiding") PLInst _lInst_)
    {
        // Constructor
        setInst(_inst_);

        setLInst(_lInst_);

    }

    @Override
    public Object clone()
    {
        return new ALInstLInst(
            cloneNode(this._inst_),
            cloneNode(this._lInst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALInstLInst(this);
    }

    public PInst getInst()
    {
        return this._inst_;
    }

    public void setInst(PInst node)
    {
        if(this._inst_ != null)
        {
            this._inst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inst_ = node;
    }

    public PLInst getLInst()
    {
        return this._lInst_;
    }

    public void setLInst(PLInst node)
    {
        if(this._lInst_ != null)
        {
            this._lInst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lInst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inst_)
            + toString(this._lInst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inst_ == child)
        {
            this._inst_ = null;
            return;
        }

        if(this._lInst_ == child)
        {
            this._lInst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inst_ == oldChild)
        {
            setInst((PInst) newChild);
            return;
        }

        if(this._lInst_ == oldChild)
        {
            setLInst((PLInst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
