/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANotExpr5 extends PExpr5
{
    private TNot _not_;
    private PExpr5 _expr5_;

    public ANotExpr5()
    {
        // Constructor
    }

    public ANotExpr5(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PExpr5 _expr5_)
    {
        // Constructor
        setNot(_not_);

        setExpr5(_expr5_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpr5(
            cloneNode(this._not_),
            cloneNode(this._expr5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpr5(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PExpr5 getExpr5()
    {
        return this._expr5_;
    }

    public void setExpr5(PExpr5 node)
    {
        if(this._expr5_ != null)
        {
            this._expr5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._expr5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._expr5_ == child)
        {
            this._expr5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._expr5_ == oldChild)
        {
            setExpr5((PExpr5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
