/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TDo extends Token
{
    public TDo()
    {
        super.setText("faire");
    }

    public TDo(int line, int pos)
    {
        super.setText("faire");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDo text.");
    }
}
