/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TEps extends Token
{
    public TEps()
    {
        super.setText("epsilon");
    }

    public TEps(int line, int pos)
    {
        super.setText("epsilon");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEps(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEps(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEps text.");
    }
}
