<Start>
 <ALdecfoncProgramme>
  <ALdecfoncrecListedecfonc>
   <AInstrDecfonc>
    <AAvecparamListeparam>
     <ADecvarListedecvar>
      <ADecvarentierDecvar>
      </ADecvarentierDecvar>
     </ADecvarListedecvar>
    </AAvecparamListeparam>
    <AInstrbloc>
     <ALinstfinalListeinst>
     </ALinstfinalListeinst>
    </AInstrbloc>
   </AInstrDecfonc>
   <ALdecfoncrecListedecfonc>
    <AInstrDecfonc>
     <ASansparamListeparam>
     </ASansparamListeparam>
     <AInstrbloc>
      <ALinstrecListeinst>
       <AInstrappelInstr>
        <AInstrappel>
         <AAppelfct>
          <AFinalListeexp>
          </AFinalListeexp>
         </AAppelfct>
        </AInstrappel>
       </AInstrappelInstr>
       <ALinstfinalListeinst>
       </ALinstfinalListeinst>
      </ALinstrecListeinst>
     </AInstrbloc>
    </AInstrDecfonc>
    <ALdecfoncfinalListedecfonc>
    </ALdecfoncfinalListedecfonc>
   </ALdecfoncrecListedecfonc>
  </ALdecfoncrecListedecfonc>
 </ALdecfoncProgramme>
</Start>
