<Start>
 <ALdecfoncProgramme>
  <ALdecfoncrecListedecfonc>
   <AInstrDecfonc>
    <ASansparamListeparam>
    </ASansparamListeparam>
    <AInstrbloc>
     <ALinstrecListeinst>
      <AInstrecritureInstr>
       <AInstrecriture>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <ANombreExp6>
              </ANombreExp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </AInstrecriture>
      </AInstrecritureInstr>
      <ALinstfinalListeinst>
      </ALinstfinalListeinst>
     </ALinstrecListeinst>
    </AInstrbloc>
   </AInstrDecfonc>
   <ALdecfoncrecListedecfonc>
    <ADecvarinstrDecfonc>
     <ASansparamListeparam>
     </ASansparamListeparam>
     <AOptdecvar>
      <ADecvarListedecvar>
       <ADecvarentierDecvar>
       </ADecvarentierDecvar>
      </ADecvarListedecvar>
     </AOptdecvar>
     <AInstrbloc>
      <ALinstrecListeinst>
       <AInstraffectInstr>
        <AInstraffect>
         <AVarsimpleVar>
         </AVarsimpleVar>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AExp5Exp4>
              <AExp6Exp5>
               <AAppelfctExp6>
                <AAppelfct>
                 <AFinalListeexp>
                 </AFinalListeexp>
                </AAppelfct>
               </AAppelfctExp6>
              </AExp6Exp5>
             </AExp5Exp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
        </AInstraffect>
       </AInstraffectInstr>
       <ALinstfinalListeinst>
       </ALinstfinalListeinst>
      </ALinstrecListeinst>
     </AInstrbloc>
    </ADecvarinstrDecfonc>
    <ALdecfoncfinalListedecfonc>
    </ALdecfoncfinalListedecfonc>
   </ALdecfoncrecListedecfonc>
  </ALdecfoncrecListedecfonc>
 </ALdecfoncProgramme>
</Start>
