<Start>
 <ALdecfoncProgramme>
  <ALdecfoncrecListedecfonc>
   <AInstrDecfonc>
    <ASansparamListeparam>
    </ASansparamListeparam>
    <AInstrbloc>
     <ALinstrecListeinst>
      <AInstrecritureInstr>
       <AInstrecriture>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AFoisExp4>
             <AFoisExp4>
              <AExp5Exp4>
               <AExp6Exp5>
                <ANombreExp6>
                </ANombreExp6>
               </AExp6Exp5>
              </AExp5Exp4>
              <AExp6Exp5>
               <ANombreExp6>
               </ANombreExp6>
              </AExp6Exp5>
             </AFoisExp4>
             <AExp6Exp5>
              <ANombreExp6>
              </ANombreExp6>
             </AExp6Exp5>
            </AFoisExp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </AInstrecriture>
      </AInstrecritureInstr>
      <ALinstfinalListeinst>
      </ALinstfinalListeinst>
     </ALinstrecListeinst>
    </AInstrbloc>
   </AInstrDecfonc>
   <ALdecfoncfinalListedecfonc>
   </ALdecfoncfinalListedecfonc>
  </ALdecfoncrecListedecfonc>
 </ALdecfoncProgramme>
</Start>
