<Start>
 <ALdecfoncProgramme>
  <ALdecfoncrecListedecfonc>
   <AInstrDecfonc>
    <ASansparamListeparam>
    </ASansparamListeparam>
    <AInstrbloc>
     <ALinstrecListeinst>
      <AInstrecritureInstr>
       <AInstrecriture>
        <AOuExp>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AExp5Exp4>
              <AExp6Exp5>
               <ANombreExp6>
               </ANombreExp6>
              </AExp6Exp5>
             </AExp5Exp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
         <AEtExp1>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AExp5Exp4>
              <AExp6Exp5>
               <ANombreExp6>
               </ANombreExp6>
              </AExp6Exp5>
             </AExp5Exp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <ANombreExp6>
              </ANombreExp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AEtExp1>
        </AOuExp>
       </AInstrecriture>
      </AInstrecritureInstr>
      <ALinstfinalListeinst>
      </ALinstfinalListeinst>
     </ALinstrecListeinst>
    </AInstrbloc>
   </AInstrDecfonc>
   <ALdecfoncfinalListedecfonc>
   </ALdecfoncfinalListedecfonc>
  </ALdecfoncrecListedecfonc>
 </ALdecfoncProgramme>
</Start>
