<Start>
 <AProgramme>
  <AEpsilon5LDeclarationVarBOpt>
  </AEpsilon5LDeclarationVarBOpt>
  <ALFunctionDecLFunctionDec>
   <AFunctionDec>
    <AEpsilon4LDeclarationVar>
    </AEpsilon4LDeclarationVar>
    <AEpsilon5LDeclarationVarBOpt>
    </AEpsilon5LDeclarationVarBOpt>
    <AIblock>
     <ALInstLInst>
      <AIwriteInst>
       <AIwrite>
        <ALExprLExpr>
         <AExpr1Expr>
          <AExpr2Expr1>
           <AExpr3Expr2>
            <AExpr4Expr3>
             <AExpr5Expr4>
              <AExpr6Expr5>
               <ANumberExpr6>
               </ANumberExpr6>
              </AExpr6Expr5>
             </AExpr5Expr4>
            </AExpr4Expr3>
           </AExpr3Expr2>
          </AExpr2Expr1>
         </AExpr1Expr>
         <AEpsilon3LExprB>
         </AEpsilon3LExprB>
        </ALExprLExpr>
       </AIwrite>
      </AIwriteInst>
      <AEpsilon1LInst>
      </AEpsilon1LInst>
     </ALInstLInst>
    </AIblock>
   </AFunctionDec>
   <AEpsilon6LFunctionDec>
   </AEpsilon6LFunctionDec>
  </ALFunctionDecLFunctionDec>
 </AProgramme>
</Start>
